// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8P8L2Au2QrFiAC4uiWkyqJiCdF1aIKyM',
    appId: '1:877118872871:web:1ad94789390e74819c1d02',
    messagingSenderId: '877118872871',
    projectId: 'withpet-637ae',
    authDomain: 'withpet-637ae.firebaseapp.com',
    storageBucket: 'withpet-637ae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDfbDTzgDMulHxdYdtBj31DfnNAzpuC4c',
    appId: '1:877118872871:android:4bc292a4054746289c1d02',
    messagingSenderId: '877118872871',
    projectId: 'withpet-637ae',
    storageBucket: 'withpet-637ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3rTk1T4m-I0QTlxGA9th-KVzLkPJc2zg',
    appId: '1:877118872871:ios:4dd50bff43c827c99c1d02',
    messagingSenderId: '877118872871',
    projectId: 'withpet-637ae',
    storageBucket: 'withpet-637ae.firebasestorage.app',
    iosBundleId: 'com.withpet.suhyeon.withpet',
  );
}
